name: Auto-format & Lint

on:
  push:
  pull_request:

jobs:
  format-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install formatters & linter
        run: |
          python -m pip install --upgrade pip
          pip install black==23.12.1 isort==5.13.2 flake8==6.1.0
      - name: Run Black (auto-fix)
        run: black --line-length 100 .
      - name: Run isort (auto-fix)
        run: isort --profile black --line-length 100 .
      - name: Commit changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-format with black+isort"
      - name: Flake8 (light rules)
        run: flake8 --max-line-length 100 --extend-ignore=E203,E266,E501,W503
