name: Lint (pre-commit)

on:
  push:
    paths: ['**.py', '.pre-commit-config.yaml', 'dev-requirements.txt']
  pull_request:
    paths: ['**.py', '.pre-commit-config.yaml', 'dev-requirements.txt']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dev deps
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure
