name: PySpark CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Java (OpenJDK 17 for PySpark)
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jre-headless

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data prep
        run: python src/01_data_prep.py

      - name: Run EDA & SQL
        run: python src/02_eda_sql.py

      - name: Run models
        run: python src/03_models.py

      - name: Upload figures
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: figures
          path: figures

      - name: Upload outputs (metrics + SQL results)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs
